<script lang="ts">
  // SPDX-License-Identifier: AGPL-3.0-or-later
  import { Dialog } from "bits-ui";

  type PageEntry = { title: string; description: string; href: string; section: string };
  type Result = { title: string; excerpt: string; href: string; meta?: string };

  type Props = {
    /** Every docs page, used as the offline index (and as the dev-mode index). */
    pages: PageEntry[];
  };

  let { pages }: Props = $props();

  let open = $state(false);
  let query = $state("");
  let results = $state<Result[]>([]);
  let searching = $state(false);
  /** Pagefind only exists in a built site; dev falls back to title matching. */
  let pagefind = $state<any>(null);
  let pagefindTried = false;

  const isMac = typeof navigator !== "undefined" && /Mac|iPhone|iPad/.test(navigator.platform);

  async function loadPagefind() {
    if (pagefindTried) return;
    pagefindTried = true;
    try {
      // Vite must not try to resolve this at build time — the bundle is
      // generated by the `pagefind` CLI after Astro has written dist/.
      const mod = await import(/* @vite-ignore */ `${location.origin}/pagefind/pagefind.js`);
      await mod.options?.({ excerptLength: 24 });
      pagefind = mod;
    } catch {
      pagefind = null; // Dev server, or the index was never generated.
    }
  }

  function fallbackSearch(q: string): Result[] {
    const needle = q.toLowerCase();
    return pages
      .filter(
        (p) =>
          p.title.toLowerCase().includes(needle) ||
          p.description.toLowerCase().includes(needle) ||
          p.section.toLowerCase().includes(needle),
      )
      .slice(0, 12)
      .map((p) => ({ title: p.title, excerpt: p.description, href: p.href, meta: p.section }));
  }

  async function run(q: string) {
    if (!q.trim()) {
      results = [];
      return;
    }
    searching = true;
    await loadPagefind();
    if (pagefind) {
      const search = await pagefind.search(q);
      const found = await Promise.all(search.results.slice(0, 12).map((r: any) => r.data()));
      results = found.map((d: any) => ({
        title: d.meta?.title ?? d.url,
        excerpt: d.excerpt,
        href: d.url.replace(/\.html$/, "/"),
        meta: d.meta?.section,
      }));
    } else {
      results = fallbackSearch(q);
    }
    searching = false;
  }

  // Debounced so typing doesn't fire a query per keystroke.
  let timer: ReturnType<typeof setTimeout>;
  $effect(() => {
    const q = query;
    clearTimeout(timer);
    timer = setTimeout(() => run(q), 120);
    return () => clearTimeout(timer);
  });

  function onkeydown(e: KeyboardEvent) {
    if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      open = !open;
    }
  }
</script>

<svelte:window {onkeydown} />

<Dialog.Root bind:open>
  <!-- Collapses to an icon-only square below `sm`, where a labelled search
       field would crowd out the nav — never hidden, search always reachable. -->
  <Dialog.Trigger
    aria-label="Search docs"
    class="inline-flex h-9 w-9 items-center justify-center gap-2 rounded-input border border-border-input bg-background-alt px-0 text-sm text-muted-foreground shadow-btn transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-2 focus-visible:ring-offset-background sm:w-56 sm:justify-start sm:px-3"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      class="size-4 shrink-0"
      aria-hidden="true"
    >
      <circle cx="11" cy="11" r="8" /><path d="m21 21-4.3-4.3" />
    </svg>
    <span class="hidden flex-1 text-left sm:inline">Search docs</span>
    <kbd
      class="hidden shrink-0 rounded-5px border border-border bg-background px-1.5 py-px font-mono text-xxs text-muted-foreground shadow-kbd sm:inline-block"
    >
      {isMac ? "⌘" : "Ctrl"} K
    </kbd>
  </Dialog.Trigger>

  <Dialog.Portal>
    <Dialog.Overlay
      class="fixed inset-0 z-50 bg-black/60"
    />
    <Dialog.Content
      class="fixed left-1/2 top-[12vh] z-50 w-[calc(100vw-2rem)] max-w-xl -translate-x-1/2 rounded-card border border-border bg-background p-1.5 shadow-popover outline-none"
    >
      <Dialog.Title class="sr-only">Search the documentation</Dialog.Title>
      <Dialog.Description class="sr-only">
        Find a page by title or content. Press Escape to close.
      </Dialog.Description>

      <div class="flex items-center gap-2 border-b border-border px-3">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="size-4 shrink-0 text-muted-foreground"
          aria-hidden="true"
        >
          <circle cx="11" cy="11" r="8" /><path d="m21 21-4.3-4.3" />
        </svg>
        <!-- svelte-ignore a11y_autofocus -->
        <input
          autofocus
          bind:value={query}
          placeholder="Search the documentation…"
          aria-label="Search query"
          class="h-11 w-full bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none"
        />
      </div>

      <div class="max-h-[55vh] overflow-y-auto p-1.5">
        {#if !query.trim()}
          <p class="px-3 py-6 text-center text-sm text-muted-foreground">
            Start typing to search every page.
          </p>
        {:else if searching && results.length === 0}
          <p class="px-3 py-6 text-center text-sm text-muted-foreground">Searching…</p>
        {:else if results.length === 0}
          <p class="px-3 py-6 text-center text-sm text-muted-foreground">
            No results for <span class="text-foreground">"{query}"</span>.
          </p>
        {:else}
          <ul class="flex flex-col gap-0.5">
            {#each results as result (result.href)}
              <li>
                <a
                  href={result.href}
                  class="block rounded-card px-3 py-2.5 transition-colors hover:bg-muted focus-visible:bg-muted focus-visible:outline-none"
                >
                  <span class="flex items-baseline gap-2">
                    <span class="text-sm font-medium text-foreground">{result.title}</span>
                    {#if result.meta}
                      <span class="text-xxs uppercase tracking-wide text-muted-foreground">
                        {result.meta}
                      </span>
                    {/if}
                  </span>
                  <span class="mt-0.5 line-clamp-2 block text-[13px] text-muted-foreground">
                    <!-- Pagefind returns highlighted HTML; the fallback is plain text. -->
                    {@html result.excerpt}
                  </span>
                </a>
              </li>
            {/each}
          </ul>
        {/if}
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>
